### ISSUE TITLE
No docs

### ISSUE THREAD

**Issue by katie-oh** [AdobeDocs/dynamic-media-developer-resources.en#1]
Issue in help/aem-is-ir-api/is-api/image-catalog/image-serving-api-ref/c-image-catalog-reference/c-image-svg-data-reference/c-image-data-reference/r-path-cat.md

**Comment by rickbrough** [comment]
Fixed. See https://docs.adobe.com/content/help/en/dynamic-media-developer-resources/image-serving-api/image-serving-api/image-svg-ref/image-data-reference/r-path-cat.html
