### ISSUE TITLE
input should be getAssetsParam and not getAssetParam

### ISSUE THREAD

**Issue by etomaello** [AdobeDocs/dynamic-media-developer-resources.en#2]
Issue in ./help/aem-ips-api/operations/c-operations-intro/c-methods/r-get-assets.md

**Comment by anujkapo** [comment]
Thanks, @etomaello. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
Closing, this was fixed.
