### ISSUE TITLE
How can I get the number of catalogs associated with a product?

### ISSUE THREAD

**Issue by fcarrasco92** [AdobeDocs/dynamic-media-developer-resources.en#2]
Issue in help/aem-is-ir-api/is-api/http-ref/image-serving-api-ref/c-http-protocol-reference/c-command-reference/r-req/r-req.md

I want to get the number or list of catalogs set for one product in scene7, the documentation doesn't help me.
only return the list of pages.

please help me

**Comment by bohnertchris** [comment]
Hello, @fcarrasco92 . Thanks for taking time to raise an issue, but documentation-related issues are for corrections or improvements to the docs themselves. If you have an implementation-related question, we kindly ask you to raise a support ticket to talk over your case with customer care. Thank you.
