### ISSUE TITLE
The referenced examples aren't available.

### ISSUE THREAD

**Issue by pmargiot** [AdobeDocs/dynamic-media-developer-resources.en#3]
Issue in help/aem-is-ir-api/ir-api/image-rendering-api-ref/r-examples-ir.md

When clicking any of the links on the page to view the image rendering examples, I get a page not found.

**Comment by bohnertchris** [comment]
Thank you for reporting this to us, @pmargiot . We will get this fixed as soon as possible.

**Comment by rickbrough** [comment]
The image rendering examples will not be fixed; the page has since been removed from the api.

**Comment by bohnertchris** [comment]
CQDOC-15622
